.TH "lib/shell_lib/include/Shell_Lib.hpp" 3 "Sat Feb 18 2023" "Version v0.01" "DSFS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/shell_lib/include/Shell_Lib.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Disk\&.hpp'\fP
.br
\fC#include 'File_System\&.hpp'\fP
.br
\fC#include <unordered_map>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBShell_lib\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DSFS from the source code\&.
