.TH "Shell_lib" 3 "Sat Feb 18 2023" "Version v0.01" "DSFS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shell_lib
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Shell_Lib\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBShell_lib\fP (int, char *[])"
.br
.ti -1c
.RI "void \fBRun\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB13\fP of file \fBShell_Lib\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Shell_lib::Shell_lib (int c_argc, char * c_argv[])"

.PP
Definition at line \fB14\fP of file \fBShell_Lib\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Shell_lib::Run ()"

.PP
Definition at line \fB46\fP of file \fBShell_Lib\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DSFS from the source code\&.
